version: "3.9"
services:
  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    image: frontend:latest
    network_mode: host
    depends_on:
      - backend

  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile
    image: backend:latest
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    network_mode: host
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15.0-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=backend
    volumes:
      - db:/var/lib/postgresql/data
    network_mode: host
    healthcheck:
      test: pg_isready -U postgres
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak-initializer:
    container_name: keycloakInitializer
    build:
      context: keycloakInitializer
      dockerfile: Dockerfile
    image: keycloakinitializer:latest
    network_mode: host
    depends_on:
      keycloak:
        condition: service_healthy

  keycloak:
    image: quay.io/keycloak/keycloak:20.0.1
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=mysql
      - KC_DB_URL_HOST=localhost
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=password
    command: start-dev
    network_mode: host
    depends_on:
      keycloak-db:
        condition: service_healthy
    healthcheck:
      test: "curl -f http://localhost:8080/admin || exit 1"

  keycloak-db:
    image: mysql:8.0.31
    container_name: keycloak-db
    environment:
      - MYSQL_DATABASE=keycloak
      - MYSQL_USER=keycloak
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - keycloak_db:/var/lib/mysql
    network_mode: host
    healthcheck:
      test: "mysqladmin ping -u root -p$${MYSQL_ROOT_PASSWORD}"

volumes:
  db:
    driver: local
  keycloak_db:
    driver: local