version: "3.9"
services:
  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    image: frontend:latest
    ports:
      - '3000:3000'
    networks:
      - network
    depends_on:
      - backend
  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile
    image: backend:latest
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/backend
    ports:
      - '8080:8080'
    networks:
      - network
    depends_on:
      - db
  db:
    image: postgres:15.0-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=backend
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - network
    healthcheck:
      test: pg_isready -U postgres
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  network:
    driver: bridge

volumes:
  db:
    driver: local