spring:
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: ${app.jwt.issuer-uri}
          jwk-set-uri: ${app.jwt.issuer-uri}/protocol/openid-connect/certs
#          public-key-location: classpath:keycloak-key.pub

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include:
          - health
          - info
  endpoint:
    health:
      enabled: true
      show-details: "when-authorized"
      roles:
        - "ADMIN"
    info:
      enabled: true
  info:
    env:
      enabled: true

info:
  app:
    encoding: "@project.build.sourceEncoding@"
    java:
      source: "@java.version@"
      target: "@java.version@"

springdoc:
  show-actuator: true
  swagger-ui:
    tryItOutEnabled: true
    operationsSorter: method
    tagsSorter: alpha
    filter: true

app:
  cors:
    allowed-origins: http://localhost:3000
  jwt:
    keycloak: http://localhost:8443
    realm: app
    issuer-uri: ${app.jwt.keycloak}/realms/${app.jwt.realm}
    resource-client-id: frontend-web

logging:
  level:
    com.example.backend: DEBUG

---

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://db:5432/backend
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # (create, create-drop, validate, update)

app:
  jwt:
    keycloak: http://keycloak:8443

---

spring:
  config:
    activate:
      on-profile: local

  h2:
    console.enabled: false # http://localhost:8080/h2-console
  datasource:
    url: jdbc:h2:mem:db
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
