logging:
  level:
    com.example.backend: DEBUG

server:
  port: 8081

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${app.jwt.issuer-uri}
          jwk-set-uri: ${app.jwt.issuer-uri}/protocol/openid-connect/certs

app:
  cors:
    allowed-origins: http://127.0.0.1:3000
  jwt:
    issuer-uri: http://127.0.0.1:8080/realms/app
    resource-client-ids: frontend-web

---

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://db:5432/backend
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL81Dialect
    hibernate:
      ddl-auto: update # (create, create-drop, validate, update)

app:
  jwt:
    issuer-uri: http://keycloak:8080/realms/app

---

spring:
  config:
    activate:
      on-profile: local

  h2:
    console.enabled: true # http://127.0.0.1:8080/h2-console
  datasource:
    url: jdbc:h2:mem:db
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
